routes/web.php
<?php

Route::get('/', 'FormController@welcome')->name('welcome');
Route::get('form/search', 'FormController@search')->name('form.search');
Route::resource('form', 'FormController');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class User extends Model
{
  protected $fillable = ['name', 'surname', 'patronymic', 'phone'];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/FormController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
class FormController extends Controller
{

  public function welcome()
  {
    return view('welcome');
  }

  public function index()
  {
    $form = User::all();
    return view('index', compact('form'));
  }

  public function create()
  {
      return view('create');
  }

  public function store(Request $request)
  {
    User::create($request->all());
    return redirect()->route('form.index');
  }

  public function edit($id)
  {
    $form = User::find($id);
    return view('edit', compact('form'));
  }

  public function update(Request $request, $id)
  {
    $user = User::find($id);
    $user->update($request->all());
    return redirect()->route('form.index');
  }

  public function destroy($id)
  {
    User::destroy($id);
    return redirect()->route('form.index');
  }

  public function search(Request $request)
  {
    $form = User::where('phone', 'like', "%$request->phone%")->get();
    return view('index', compact('form'));
   }
}

resources/views/create.blade.php
@extends('layouts.app')
@section('container')
    <h2>Введите данные новой записи</h2>
    <form action="{{ route('form.store') }}" method="POST">
        {{ csrf_field() }}
        Фамилия
        <input class="input_create" type="text" name="surname" required><br>
        Имя
        <input class="input_create" type="text" name="name" required><br>
        Отчество
        <input class="input_create" type="text" name="patronymic" required><br>
        Телефон
        <input class="input_create" type="text" name="phone" required><br>
        <input class="input_create" type="hidden" name="id" required><br>
        <input class="input_create" type="submit" value="добавить запись">
    </form>
@endsection

resources/views/edit.blade.php
@extends('layouts.app')
@section('container')
    <h2>Пожалуйста, отредактируйте нужные Вам данные</h2>
    <form action="{{ route('form.update', $form->id) }}" method="post" >
        {{ csrf_field() }}
        {{ method_field('PUT') }}
        Фамилия
        <input class="input_create" type="text" name="surname" value="{{ $form->surname }}" required><br>
        Имя
        <input class="input_create" class="input_create" type="text" name="name" value="{{ $form->name }}" required><br>
        Отчество
        <input class="input_create" type="text" name="patronymic" value="{{ $form->patronymic }}" required><br>
        Телефон
        <input class="input_create" type="text" name="phone" value="{{ $form->phone }}" required><br>
        <input class="input_create" type="hidden" name="id" value="{{ $form->id }}" required><br>
        <input class="input_create" type="submit" value="обновить запись">
    </form>
@endsection

resources/views/index.blade.php
@extends('layouts.app')
@section('container')


    <form action="{{ route('form.search') }}">
        <input class="input_create" type="text" name="phone" placeholder="Введите номер для поиска">
        <input type="submit" value="search">
    </form>

    <table class="item">
        <tr>
            <th>№п/п</th>
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Отчество</th>
            <th>Телефон</th>
            <th>Edit</th>
        </tr>

        @forelse ($form as $item)
            <tr>
                <td>{{ $loop->iteration }}</td>
                <td>{{ $item->surname }}</td>
                <td>{{ $item->name }}</td>
                <td>{{ $item->patronymic }}</td>
                <td>{{ $item->phone }}</td>
                <td>
                    <form action="{{ route('form.edit', $item->id) }}">
                        <input type="submit" value="edit">
                    </form>
                    <form action="{{ route('form.destroy', $item->id) }}" method="POST">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                        <input type="submit" value="delete">
                    </form>
                </td>
            </tr>
        @empty
            <h2>Такого номера не существует</h2>
        @endforelse
        <hr>
    </table>
    <a href="{{ route('form.create') }}">Добавить контакт в таблицу </a>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <title>Laravel</title>
    <link rel="stylesheet" type="text/css" href="{{ asset('css/style.css') }}">
</head>
<body>
<div class="container">
    @section('container')
    @show
</div>
</body>
</html>